packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  protobufjs: false
  workerd: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
  - '@react-three/drei@10.7.9'
  - '@react-three/fiber@9.8.1'
  - framer-motion@13.4.4
  - its-fine@2.1.1
  - motion-dom@13.4.4
  - motion@13.4.4
  - '@cortex-js/compute-engine@0.135.0'
