import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { course, plates } from "../src";
import { CHECKS, publishChecklist, publishReport } from "../src/report";

const here = dirname(fileURLToPath(import.meta.url));

describe("publish checklist", () => {
  it("the showcase concept passes every item", () => {
    const gauss = course.concepts.find((c) => c.id === "em1.electrostatics.gauss-law")!;
    const r = publishChecklist(course, gauss, plates);
    expect(CHECKS.filter((k) => !r[k])).toEqual([]);
  });

  it("every unlocked concept has objectives, sources, a formal statement and practice", () => {
    for (const c of course.concepts.filter((x) => !x.locked)) {
      const r = publishChecklist(course, c, plates);
      expect([r.objectives, r.sources, r["formal statement"], r.practice], c.id).toEqual([true, true, true, true]);
    }
  });

  it("writes the report for human review", () => {
    const md = `# Publish report: ${course.title}\n\nGenerated by \`pnpm test\`. ✓ = present, · = missing.\n\n${publishReport(course, plates)}\n`;
    writeFileSync(join(here, "..", "PUBLISH_REPORT.md"), md);
    expect(md).toContain("Gauss's Law");
  });
});
